[package]
name = "c-to-rust"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
build = "build.rs"

[lib]
name = "double_input"
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.9.*"
